"""init db

Revision ID: 4dc05119e4a9
Revises: 
Create Date: 2024-02-06 13:31:55.186570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc05119e4a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None





def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('surveys',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('survey_type', sa.String(length=256), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_table('user_addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('survey_feedbacks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.Text(), nullable=True),
    sa.Column('question2', sa.Text(), nullable=True),
    sa.Column('question3', sa.Text(), nullable=True),
    sa.Column('question4', sa.Text(), nullable=True),
    sa.Column('question5', sa.Text(), nullable=True),
    sa.Column('question6', sa.Text(), nullable=True),
    sa.Column('question7', sa.Text(), nullable=True),
    sa.Column('question8', sa.Text(), nullable=True),
    sa.Column('question9', sa.Text(), nullable=True),
    sa.Column('deep_url', sa.String(length=256), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'building_id', 'survey_id')
    )

    op.execute("""
    INSERT INTO users (user_id, telegram_id) VALUES
    (1, 123456789),
    (2, 987654321),
    (3, NULL),
    (4, 456789123),
    (5, NULL),
    (6, 234567890),
    (7, 345678901),
    (8, NULL),
    (9, 567890123),
    (10, 678901234),
    (11, NULL),
    (12, 789012345),
    (13, 890123456),
    (14, NULL),
    (15, 901234567),
    (16, 112233445),
    (17, NULL),
    (18, 556677889),
    (19, 667788990),
    (20, NULL);
    """)

    op.execute(
        """
        INSERT INTO buildings (building_id, building_name) VALUES
        (1, 'Building Alpha'),
        (2, 'Building Beta'),
        (3, 'Building Gamma'),
        (4, 'Building Delta'),
        (5, 'Building Epsilon'),
        (6, 'Building Zeta'),
        (7, 'Building Eta'),
        (8, 'Building Theta'),
        (9, 'Building Iota'),
        (10, 'Building Kappa'),
        (11, 'Building Lambda'),
        (12, 'Building Mu'),
        (13, 'Building Nu'),
        (14, 'Building Xi'),
        (15, 'Building Omicron'),
        (16, 'Building Pi'),
        (17, 'Building Rho'),
        (18, 'Building Sigma'),
        (19, 'Building Tau'),
        (20, 'Building Upsilon');
        """
    )

    op.execute("""
    INSERT INTO user_addresses (address_id, user_id, building_id, apartment_number) VALUES
    (1, 1, 1, '101'),
    (2, 2, 2, '102'),
    (3, 3, 3, NULL),
    (4, 4, 4, '104'),
    (5, 5, 5, NULL),
    (6, 6, 6, '106'),
    (7, 7, 7, '107'),
    (8, 8, 8, NULL),
    (9, 9, 9, '109'),
    (10, 10, 10, '110'),
    (11, 11, 11, NULL),
    (12, 12, 12, '112'),
    (13, 13, 13, '113'),
    (14, 14, 14, NULL),
    (15, 15, 15, '115'),
    (16, 16, 16, '116'),
    (17, 17, 17, NULL),
    (18, 18, 18, '118'),
    (19, 19, 19, '119'),
    (20, 20, 20, NULL);
    """)



    op.execute("""
    INSERT INTO surveys (survey_id, building_id, opened, survey_type) VALUES
    (1, 1, True, 'Співробітники'),
    (2, 2, True, 'Мешканці'),
    (3, 3, True, 'Співробітники'),
    (4, 4, True, 'Мешканці'),
    (5, 5, True, 'Співробітники'),
    (6, 6, True, 'Мешканці'),
    (7, 7, True, 'Співробітники'),
    (8, 8, True, 'Мешканці'),
    (9, 9, True, 'Співробітники'),
    (10, 10, True, 'Мешканці'),
    (11, 11, True, 'Співробітники'),
    (12, 12, True, 'Мешканці'),
    (13, 13, True, 'Співробітники'),
    (14, 14, True, 'Мешканці'),
    (15, 15, True, 'Співробітники'),
    (16, 16, True, 'Мешканці'),
    (17, 17, True, 'Співробітники'),
    (18, 18, True, 'Мешканці'),
    (19, 19, True, 'Співробітники'),
    (20, 20, True, 'Мешканці');
    """)

    op.execute("""
    INSERT INTO survey_feedbacks (user_id, building_id, survey_id, question1, question2, question3, question4, question5, question6, question7, question8, question9, deep_url) VALUES
    (1, 1, 1, 'Да', 'Нет', 'Нет', 'Да', NULL, 'Возможно', NULL, 'Нет', 'Да', 'https://example.com/feedback/1'),
    (2, 2, 1, 'Нет', 'Да', 'Да', NULL, 'Возможно', NULL, 'Да', 'Нет', NULL, 'https://example.com/feedback/2'),
    (3, 3, 1, 'Возможно', NULL, 'Да', 'Нет', 'Да', NULL, 'Нет', 'Да', NULL, 'https://example.com/feedback/3'),
    (4, 4, 1, NULL, 'Да', NULL, 'Возможно', 'Нет', 'Да', NULL, 'Да', 'Нет', 'https://example.com/feedback/4'),
    (5, 5, 1, 'Да', NULL, 'Возможно', 'Да', NULL, 'Нет', 'Да', NULL, 'Возможно', 'https://example.com/feedback/5'),
    (6, 1, 2, 'Нет', 'Да', 'Возможно', NULL, 'Да', 'Нет', NULL, 'Да', 'Возможно', 'https://example.com/feedback/6'),
    (7, 2, 2, 'Да', 'Нет', NULL, 'Да', 'Возможно', 'Да', 'Нет', NULL, 'Да', 'https://example.com/feedback/7'),
    (8, 3, 2, NULL, 'Возможно', 'Да', 'Нет', 'Да', NULL, 'Да', 'Нет', 'Возможно', 'https://example.com/feedback/8'),
    (9, 4, 2, 'Да', 'Да', NULL, 'Возможно', 'Нет', 'Да', NULL, 'Возможно', 'Да', 'https://example.com/feedback/9'),
    (10, 5, 2, 'Нет', NULL, 'Да', 'Да', 'Возможно', NULL, 'Нет', 'Да', 'Нет', 'https://example.com/feedback/10'),
    (11, 1, 3, 'Возможно', 'Да', 'Нет', NULL, 'Да', 'Возможно', 'Да', NULL, 'Нет', 'https://example.com/feedback/11'),
    (12, 2, 3, 'Да', 'Нет', 'Возможно', 'Да', NULL, 'Да', 'Нет', 'Возможно', NULL, 'https://example.com/feedback/12'),
    (13, 3, 3, 'Нет', 'Да', NULL, 'Возможно', 'Да', 'Нет', 'Да', NULL, 'Возможно', 'https://example.com/feedback/13'),
    (14, 4, 3, 'Да', 'Возможно', 'Да', NULL, 'Нет', 'Да', 'Возможно', 'Нет', NULL, 'https://example.com/feedback/14'),
    (15, 5, 3, 'Нет', 'Да', 'Нет', 'Да', 'Возможно', NULL, 'Да', 'Нет', 'Да', 'https://example.com/feedback/15'),
    (16, 1, 4, 'Да', NULL, 'Возможно', 'Нет', 'Да', 'Нет', 'Да', 'Возможно', NULL, 'https://example.com/feedback/16'),
    (17, 2, 4, 'Возможно', 'Да', 'Нет', 'Да', NULL, 'Возможно', 'Нет', 'Да', 'Нет', 'https://example.com/feedback/17'),
    (18, 3, 4, 'Нет', 'Возможно', 'Да', 'Нет', 'Да', NULL, 'Да', 'Нет', 'Да', 'https://example.com/feedback/18'),
    (19, 4, 4, 'Да', 'Нет', 'Возможно', 'Да', 'Возможно', 'Нет', NULL, 'Да', 'Возможно', 'https://example.com/feedback/19'),
    (20, 5, 4, 'Нет', 'Да', 'Да', 'Нет', NULL, 'Возможно', 'Да', 'Нет', 'Да', 'https://example.com/feedback/20');
    """)



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_feedbacks')
    op.drop_table('user_addresses')
    op.drop_table('surveys')
    op.drop_table('users')
    op.drop_table('buildings')
    # ### end Alembic commands ###
